services:
  - type: web
    name: flask-app
    env: python
    plan: free
    region: frankfurt

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db
          property: connectionString
      - key: SECRET_KEY
        value: supersecretkey
      - key: PYTHON_VERSION
        value: 3.13.0
